### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by valkyrka** [aogail/chef-zipfile#10]
Hi, I'm trying to use your LWRP to extract an archive. My recipe is very simple:

```
install_path = "/tmp/valkyrka"
zip_filename = "#{install_path}/app.zip"

aws_s3_file zip_filename do
    bucket node['bucket']['deployment']['name']
    remote_path "#{node['bucket']['deployment']['path']}/app.zip"
    region 'eu-west-1'
end

zipfile zip_filename do
    into '/tmp/valkyrka/extract'
    overwrite true
end
```

When I try to execute my recipe, I get the following:

```
================================================================================
    Error executing action `extract` on resource 'zipfile[/tmp/valkyrka/app.zip]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory @ rb_sysopen - /tmp/valkyrka/extract/node_modules/.bin/bunyan

    Cookbook Trace:
    ---------------
    /opt/chef-solo/cookbooks/zipfile/providers/default.rb:14:in `block (4 levels) in class_from_file'
    /opt/chef-solo/cookbooks/zipfile/providers/default.rb:12:in `block (3 levels) in class_from_file'
    /opt/chef-solo/cookbooks/zipfile/providers/default.rb:11:in `block (2 levels) in class_from_file'
    /opt/chef-solo/cookbooks/zipfile/providers/default.rb:10:in `block in class_from_file'
    /opt/chef-solo/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /opt/chef-solo/cookbooks/price-file-router/recipes/deploy.rb

     11: zipfile zip_filename do
     12:     into '/tmp/valkyrka/extract'
     13:     overwrite true
     14: end
     15:

    Compiled Resource:
    ------------------
    # Declared in /opt/chef-solo/cookbooks/price-file-router/recipes/deploy.rb:11:in `from_file'

    zipfile("/tmp/valkyrka/app.zip") do
      action [:extract]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :zipfile
      cookbook_name "price-file-router"
      recipe_name "deploy"
      into "/tmp/valkyrka/extract"
      overwrite true
      from "/tmp/valkyrka/app.zip"
    end

    Platform:
    ---------
    x86_64-linux

[2017-09-14T19:50:56+00:00] INFO: Running queued delayed notifications before re-raising exception
```
Thanks!

**Comment by aogail** [comment]
How was the zip file created? Can you post a zip file that exhibits this behavior somewhere I can access?

**Comment by valkyrka** [comment]
Hi, thanks for the follow-up. It does seem to be related to the archive. Unfortunately, there seems to be an issue with the archive itself. This is created using an internal tool. I will trim the confidential bits and get that for you. Appreciate the support.

**Comment by aogail** [comment]
Okay. I would guess that the zip file has an entry for a child of `node_modules/.bin/bunyan` before the entry for the directory itself.

**Comment by hauntingEcho** [comment]
@valkyrka - were you able to create a zip file which triggers the behavior which you can share, to use as an integration test for Bedotech's pull request?
